version: '3.8'

services:
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: owasp-zap
    ports:
      - "8181:8181"  # Map host port 8181 to container port 8181
    volumes:
      - ../config:/zap/wrk:rw  # Adjust the path to your config directory
    command: >
      zap.sh -daemon -host 0.0.0.0 -port 8181
      -config api.disablekey=true
      -config api.addrs.addr.name=.*
      -config api.accessControlAllowOrigin=*

volumes:
  db-data:
    # Configuration du volume
